steps:
  - label: ":elixir: Unit Tests"
    command: mix do clean, deps.get && mix test
    plugins:
      docker-compose:
        run: test
        config: docker-compose.ci.yml
    agents:
      queue: beta
